modLoader = "javafml"
loaderVersion = "[28,)"
license = "MIT"

[[mods]]
modId = "devauth"
version = "${version}"
displayName = "DevAuth"
authors = "DJtheRedstoner"
description = "Safely authenticate Microsoft and Mojang accounts in development environments."
logoFile = "logo.png"